"""
Problem 44

Pentagonal numbers are generated by the formula, Pn = n*(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
"""
# brute force
def isPent(n, S):
    """
    n: an int
    S: a set
    """
    if len(S) is 0:
        setSet(1, 100, S)
    
    while S[-1] < 2 * n:
        setSet(len(S)+1, len(S)+10, S)
    
    return n in S
    
def setSet(i, j, S):
    """
    i: an int
    j: an int
    S: a set
    """
    for x in range(i, j):
        Pn = int( x*(3*x-1)/2 )
        S.append(Pn)

def fitsRule(Pj, Pk, S):
    return isPent(Pj + Pk, S) and isPent(Pj - Pk, S)
    
T = []
setSet(1, 100, T)
diff = 99999999
for i in range(1, 5000):
    for j in range(1, i):
        if fitsRule(T[i], T[j], T) and (T[i] - T[j]) < diff:
            diff = T[i] - T[j]

print('end.', diff)